### ISSUE TITLE
[Muslin] Tab中表格的日期格式问题

### ISSUE THREAD

**Issue by rocgao** [rocgao/ap-stsv3#2]
@asural 
日期格式请使用yyyy/MM/dd
![2016-12-31 15-58-19](https://cloud.githubusercontent.com/assets/7875614/21576631/078e4c44-cf72-11e6-83bd-26c8980f7a91.png)

**Comment by asural** [comment]
@rocgao 意见修复详细见 82f27bdd4ad18bff5bc652804aa1087452801de5

**Comment by asural** [comment]
@rocgao 已经修复详细见 82f27bd
