### ISSUE TITLE
添加大货和NY Approval字段

### ISSUE THREAD

**Issue by rocgao** [rocgao/ap-stsv3#3]
1. 加在[Base Info] Tab
2. 根据@Model.StyleType.Code属性判断
3. 将IBlukTypeChecker和INyApprovalChecker. 通过@Injection注入到cshtml里
4. 调用IBlukTypeChecker.IsBlukAsync(typeCode)的返回值决定是否需要显示P.O.、SIze-R、Bulk Fty、Del Date、Deadline字段是否需要显示
5. 调用INyApprovalChecker.ShowNyApprovalAsync(string typeCode)的返回值决定是否需要显示app/rjt、Date、Remark字段

字段信息
![2016-12-31 20-58-18](https://cloud.githubusercontent.com/assets/7875614/21577601/e8d04efe-cf9b-11e6-876e-e1107ba8dbf5.png)

App\Rjt Combobox中的值
![2016-12-31 20-57-41](https://cloud.githubusercontent.com/assets/7875614/21577602/e8fb16c0-cf9b-11e6-9848-cce882d5cdfa.png)

选择FIT版时
![fit](https://cloud.githubusercontent.com/assets/7875614/21577604/e94d04d0-cf9b-11e6-927a-468e6ae6c748.png)

选择SR版时
![sr](https://cloud.githubusercontent.com/assets/7875614/21577603/e94b214c-cf9b-11e6-91d1-366e3536bfce.png)

**Comment by asural** [comment]
@rocgao 已经完成见f17605a62c787cba2736ded003b45697c0b055b2
